---

- name: "Setup for the AWX/Automation Controller system."
  hosts: "{{ 'awx_servers' }}"
  become: true
  gather_facts: no

  roles:
    #- awx-provision
    - awx-install
    - awx-custom-config
    - awx-backup
    - awx-monitor
    - awx-backup-rehearsal