
# Add or remove host to inventory on AWX
- import_tasks: "{{ role_path }}/tasks/update_awx.yml"
  when: backup_rehearsal_enabled | bool

# Spawns or destroys a DigitalOcean Droplet
- import_tasks: "{{ role_path }}/tasks/spawn_do_droplet.yml"
  when: backup_rehearsal_enabled | bool

# Creates or deletes a Cloudflare DNS entry
- import_tasks: "{{ role_path }}/tasks/cloudflare_dns.yml"
  when: backup_rehearsal_enabled | bool
