---

- name: Add the new AWX host to the {{ org_name }} inventory
  awx.awx.tower_host:
    name: "{{ awx_url }}"
    description: "A new AWX Server, accessed at its URL."
    inventory: "{{ org_name }}"
    state: present
    tower_host: "https://{{ host_awx_url }}"
    tower_oauthtoken: "{{ host_awx_token }}"
    validate_certs: "{{ validate_certs }}"
  ignore_errors: True

- name: Add group awx_servers
  awx.awx.tower_group:
    name: awx_servers
    description: "AWX servers."
    inventory: "{{ org_name }}"
    hosts: "{{ awx_url }}"
    state: present
    tower_host: "https://{{ host_awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"