---

- name: Copy tokens.yml file to local machine
  ansible.builtin.fetch:
    src: /data/projects/awx/tokens.yml
    dest: /tmp/tokens.yml
    flat: yes

- name: Include AWX/Automation Controller master token from awx_tokens.yml
  include_vars:
    file: /tmp/tokens.yml
  no_log: True

- name: Create a AWX session token for executing AWX modules
  awx.awx.tower_token:
    description: 'AWX Session Token'
    scope: "write"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ master_token }}"
    validate_certs: "{{ validate_certs }}"
  register: awx_session_token

- name: Add AWX host to the {{ org_name }} inventory
  awx.awx.tower_host:
    name: "{{ awx_url }}"
    description: "A new AWX Server, accessed at its URL."
    inventory: "{{ org_name }}"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"
  ignore_errors: True

- name: Delete the AWX session token for executing modules
  awx.awx.tower_token:
    description: 'AWX Session Token'
    scope: "write"
    state: absent
    existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"