---

- debug:
    msg: "{{ server_ipv4 }}"
  when: server_ipv4 is defined

- debug:
    msg: "{{ server_ipv6 }}"
  when: server_ipv6 is defined

- debug: msg="No IP address is defined, please enter the IP address of your server."
  when: ( server_ipv4 | length == 0 ) and ( server_ipv6 | length == 0 )

- meta: end_play
  when: ( server_ipv4 | length == 0 ) and ( server_ipv6 | length == 0 )

- name: Set server_ip_final if both IPv4 and IPv6 are defined.
  delegate_to: 127.0.0.1
  set_fact:
    server_ip_final: '{{ server_ipv4 }}'
  when: ( server_ipv4 | length > 0 ) and ( server_ipv6 | length > 0 )

- name: Set server_ip_final if only IPv4 is defined.
  delegate_to: 127.0.0.1
  set_fact:
    server_ip_final: '{{ server_ipv4 }}'
  when: ( server_ipv4 | length > 0 ) and ( server_ipv6 | length == 0 )

- name: Set server_ip_final if only IPv6 is defined.
  delegate_to: 127.0.0.1
  set_fact:
    server_ip_final: '{{ server_ipv6 }}'
  when: ( server_ipv4 | length == 0 ) and ( server_ipv6 | length > 0 )