
---

- debug:
    msg: "The public SSH key to check for: {{ public_ssh_key }}"

- name: Collect list of DigitalOcean public SSH keys
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_sshkey_info:
    oauth_token: '{{ do_api_token }}'
  register: ssh_keys

- debug:
    msg: "{{ ssh_keys }}"

- name: Build an array with the correct SSH key ID
  delegate_to: 127.0.0.1
  set_fact:
    ssh_key_id_array: "{{ ssh_key_id_array }} + [ '{{ item.id }}' ]"
  when: item.public_key == public_ssh_key
  loop: "{{ ssh_keys.data|flatten(levels=1) }}"

- debug:
    msg: "{{ ssh_key_id_array }}"

- name: Spawn a new Digital Ocean Droplet, collect the IPv4+IPv6 addresses
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: '{{ do_droplet_name }}'
    oauth_token: '{{ do_api_token }}'
    size: '{{ slug_size }}'
    ssh_keys: '{{ ssh_key_id_array }}'
    region: '{{ do_droplet_region }}'
    image: '{{ do_image }}'
    ipv6: yes
    wait: yes
    unique_name: yes
  register: new_server_info

- debug:
    msg: "{{ new_server_info }}"

- name: Assign server IPv4 to a variable
  delegate_to: 127.0.0.1
  set_fact:
    server_ipv4: "{{ new_server_info.data.droplet.networks.v4[0].ip_address }}"
  when: new_server_info.data.droplet.networks.v4[0].type == "public"

- name: Assign server IPv4 to a variable
  delegate_to: 127.0.0.1
  set_fact:
    server_ipv4: "{{ new_server_info.data.droplet.networks.v4[1].ip_address }}"
  when: new_server_info.data.droplet.networks.v4[1].type == "public"

- debug:
    msg: "{{ new_server_info.data.droplet.networks }}"

- name: Assign server IPv6 to a variable
  delegate_to: 127.0.0.1
  set_fact:
    server_ipv6: "{{ new_server_info.data.droplet.networks.v6[0].ip_address }}"
  when: ( new_server_info.data.droplet.networks.v6 is defined ) and ( new_server_info.data.droplet.networks.v6 | length > 0 ) and ( new_server_info.data.droplet.networks.v6[0].type == "public" )

- debug:
    msg: "{{ server_ipv4 }}"

- debug:
    msg: "{{ server_ipv6 }}"