---

#- name: Add machine credential
#  awx.awx.credential:
#    name: "AWX SSH Key"
#    description: "The SSH key for AWX to connect to its own host OS."
#    organization: "{{ org_name }}"
#    credential_type: Machine
#    state: present
#    inputs:
#      ssh_key_unlock: "{{ awx_ssh_key_password }}"
#      ssh_key_data: "{{ lookup('file', '{{ awx_ssh_key }}') }}"
#    tower_host: "https://{{ awx_url }}"
#    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
#    validate_certs: "{{ validate_certs }}"