---

- name: Add 'AWX Ansible' project to AWX admins organisation
  awx.awx.tower_project:
    name: "AWX Ansible"
    description: "An example playbook for this AWX setup."
    organization: "{{ org_name }}"
    scm_type: git
    scm_url: "{{ deploy_source }}"
    scm_branch: "{{ deploy_branch }}"
    scm_delete_on_update: yes
    scm_update_on_launch: no
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"

- name: Update 'AWX Ansible' project
  awx.awx.tower_project_update:
    name: "AWX Ansible"
    timeout: 300
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"