---

- name: Create 'Create AWX Account' job template
  awx.awx.tower_job_template:
    name: "Create AWX Account"
    description: "Provisions AWX/Ansible Controllers organisations, teams and users."
    job_type: run
    inventory: "{{ org_name }}"
    project: "Ansible Repository"
    playbook: setup.yml
    extra_vars: "{{ lookup('file', '{{ role_path }}/extra-vars/create-account.json') }}"
    ask_extra_vars: yes
    state: present
    verbosity: 1
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes

- name: Create 'Deploy All Servers' job template
  awx.awx.tower_job_template:
    name: "Deploy All Servers"
    description: "Checks for updates, then applies those upgrades to every server connected to AWX/Automation Controller."
    job_type: run
    inventory: "{{ org_name }}"
    project: "Ansible Repository"
    playbook: setup.yml
    ask_extra_vars: yes
    survey_enabled: true
    survey_spec: "{{ lookup('file', '{{ role_path }}/surveys/update_all.json') }}"
    state: present
    verbosity: 1
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes

- name: Create 'Backup All Servers' job template
  awx.awx.tower_job_template:
    name: "Backup All Servers"
    description: "Performs a sequential backup of every server connected to AWX/Automation Controller."
    job_type: run
    inventory: "{{ org_name }}"
    project: "Ansible Repository"
    playbook: setup.yml
    state: present
    verbosity: 1
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes