---

- name: Create the admin organisation
  awx.awx.tower_organization:
    name: "{{ org_name }}"
    description: "The main organisation that is used to manage other organisations."
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes

- name: Add admin user to their organisation
  awx.awx.tower_role:
    user: "admin"
    organization: "{{ org_name }}"
    role: member
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes

- name: Add inventory to the admins organisation
  awx.awx.tower_inventory:
    name: "{{ org_name }}"
    description: "{{ org_name }} inventory"
    organization: "{{ org_name }}"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes

- name: Add AWX Server inventory to the admins organisation
  awx.awx.tower_inventory:
    name: "AWX Server"
    description: "An inventory for the AWX Server itself."
    organization: "{{ org_name }}"
    state: present
    variables:
      ansible_connection: local
      ansible_python_interpreter: '{{ ansible_playbook_python }}'
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes

- name: Add localhost to the AWX Server inventory
  awx.awx.tower_host:
    name: "localhost"
    description: "The AWX/Automation Controller server itself."
    inventory: "AWX Server"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes

- name: Allow admin account to administrate/use this inventory
  awx.awx.tower_role:
    user: "admin"
    inventory: "{{ org_name }}"
    role: use
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes