---

- name: Add snap/snapd package
  ansible.builtin.package:
    pkg:
    - snap
    - snapd
  register: package_status
  until: package_status is success
  delay: 6
  retries: 10

- name: Add k9s snap for Ubuntu 22.04 or Debian 11
  community.general.snap:
    name: k9s
