---

# Do prerequisite server setup for AWX/Ansible Controller
- import_tasks: "{{ role_path }}/tasks/server_setup.yml"
  tags: [ 'never', 'setup' ]

# Setup k3s on host
- import_tasks: "{{ role_path }}/tasks/k3s_setup.yml"
  tags: [ 'never', 'setup' ]

# Deploy AWX/Automation Controller to Kubernetes
- import_tasks: "{{ role_path }}/tasks/awx_setup.yml"
  tags: [ 'never', 'setup' ]

# Setup the systems Firewall with UFW
- import_tasks: "{{ role_path }}/tasks/firewall_setup.yml"
  tags: [ 'never', 'setup-firewall']

# Deploy Rancher for Kubernetes management
- import_tasks: "{{ role_path }}/tasks/rancher_setup.yml"
  tags: [ 'never', 'setup-rancher']