---

- name: Set server hostname to AWX / Ansible Controller URL
  command: |
    hostnamectl set-hostname {{ awx_url }}

- name: Update repos
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    name: "*"
    state: latest

- name: Add prerequisite packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - gnupg2
    - software-properties-common
    - apt-listchanges
    - make