---

- name: Set server hostname to AWX / Ansible Controller URL
  command: |
    hostnamectl set-hostname {{ awx_url }}

- name: Update repos
  apt:
    update_cache: yes
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: Upgrade all packages
  apt:
    name: "*"
    state: latest
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: Add prerequisite packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - gnupg2
    - software-properties-common
    - apt-listchanges
    - make
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10