
# Organisation Settings
org_name: ExampleOrg    # Your organisations name

# URL Settings
awx_url: panel.example.org          # URL of the AWX server/service.
rancher_url: rancher.example.org    # URL of Rancher service.
certbot_email: example@email.com    # The organisations email for LetsEncrypt.

# AWX Settings
admin_username: admin
admin_password: << strong-password >> # AWX admin user password.
secret_key: << strong-password >>     # AWX secrets password.
pg_password: << strong-password >>    # AWX database password.
self_signed_certs: false

# Deploy All Settings
update_schedule_start: '20210101T000000'
update_schedule_frequency: 'HOURLY'
update_schedule_interval: 1

# Repository Settings
deploy_source: https://gitlab.com/PC-Admin/awx-ansible    # Repository of this AWX playbook
deploy_branch: main

# Rancher settings
rancher_enabled: false
rancher_password: << strong-password >>   # Rancher users password

# Backup Server Settings
backup_enabled: false
backup_server_ip: 123.456.789.255           # IP of the backup server, be sure you can ssh to it
backup_passphrase: << strong-password >>    # Borgbackup encryption passphrase
backup_retention_days: 90                   # Borgbackup retention period
backup_local_copies: 3                       # Number of local copies of the backup to store locally on the AWX Server
backup_awx_schedule_start: '20200101T000000'  # Borgbackup Job Template Schedule
backup_awx_schedule_frequency: 'HOURLY'
backup_awx_schedule_interval: 1

# Monitor Settings
monitor_enabled: false
grafana_url: grafana.example.org                    # URL of the Grafana service
grafana_com_username: << grafana.com username >>
grafana_com_token: << grafana.com API token >>
#grafana_admin_default_password: admin

# Error Reporting Settings
mailgun_enabled: true
mailgun_api_token: << Mailgun API Token >>
mailgun_domain_name: mg.example.org

# Backup Rehearsal Settings
backup_rehearsal_enabled: false
new_awx_url: awxnew.example.org
server_subdomains: ["awxnew"]
do_droplet_name: awxnew.example.org
do_droplet_region: sgp1
do_api_token: << DigitalOcean API Token >>
slug_size: s-4vcpu-8gb
swap_size: "4G"
do_image: ubuntu-22-04-x64
cloudflare_email: example@email.com
cloudflare_api_token: << Cloudflare API Token >>
cloudflare_zone_name: example.org
ssh_key_file_public: ~/.ssh/ssh_ed25519.pub
ssh_key_file_private: ~/.ssh/ssh_ed25519
ssh_key_file_password: << strong password >>
public_ssh_key: "ssh-ed25519 some public ssh key..."
