
# Organisation Settings
org_name: ExampleOrg

# URL Settings
awx_url: panel.example.org
rancher_url: rancher.example.org
certbot_email: michael@perthchat.org

# Cloudflare
cloudflare_api_key: << cloudflare API key >>
cloudflare_email: cloudflareaccount@protonmail.com

# Rancher settings
rancher_password: << strong-password >>

# AWX/Automation Controller Settings
admin_username: admin
admin_password: << strong-password >>
secret_key: << strong-password >>
pg_password: << strong-password >>

# Deploy All Settings
update_schedule_start: '20210101T000000'
update_schedule_frequency: 'HOURLY'
update_schedule_interval: 1

# Repository Settings
deploy_source: https://github.com/spantaleev/matrix-docker-ansible-deploy.git
deploy_branch: master

# Backup Server Settings
backup_enabled: false
backup_server_ip: 123.456.789.255
backup_passphrase: << strong-password >>
backup_retention_days: 90

# Monitor Settings
monitor_enabled: true
grafana_url: grafana.example.org
grafana_com_username: << grafana.com username >>
grafana_com_token: << grafana.com API token >>
grafana_admin_password: admin