---

- name: "Lists the Borgmatic backup history on the Backup Server."
  hosts: "{{ awx_url }}"
  gather_facts: false

  tasks:
    - name: "Collect a list of the local dumps on the AWX Server."
      command: rbash /data/backup/list.sh
      register: local_backup_list

    - name: "Print the list of local dumps."
      debug:
        msg: "{{ local_backup_list.stdout_lines[-6:] }}"

    - name: "Collect the Borgmatic backup history on the Backup Server."
      delegate_to: "{{ backup_server_ip }}"
      command: borg list /home/borg/AWX/
      environment:
        BORG_PASSPHRASE: "{{ BORG_PASSPHRASE }}"
      register: borgmatic_list

    - name: "Print the Borgmatic history."
      debug:
        msg: "{{ borgmatic_list.stdout_lines[-6:] }}"