---

- name: "Emails a failed jobs output to the administrator."
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Hello world!"
      debug:
        msg: "Hello world!"

    - name: List failed jobs for the testing.yml playbook
      job_list:
        status: failed
        #query: {"playbook": "testing.yml"}
        tower_host: "https://{{ awx_url }}"
        tower_oauthtoken: "{{ awx_token }}"
        validate_certs: yes
      register: failed_jobs

    - name: "Failed jobs"
      debug:
        msg: "{{ failed_jobs }}"

    - name: Send email using Mailgun API
      command: |
          curl -s --user 'api:{{ mailgun_api_token }}' \
          https://api.mailgun.net/v3/{{ mailgun_domain_name }}/messages \
          -F from='Mailgun Sandbox <postmaster@{{ mailgun_domain_name }}>' \
          -F to='Michael Collins <perthchat@protonmail.com>' \
          -F subject='Hello Michael Collins' \
          -F text='Congratulations Michael Collins, you just sent an email with Mailgun! You are truly awesome!'