---

- name: "Emails a failed jobs output to the administrator."
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - community.general

  tasks:
    - name: Collect the id of the last failed job
      command: |
          curl -H "Authorization: Bearer {{ awx_token }}" -kX GET 'https://{{ host_awx_url }}/api/v2/job_templates/?status=failed'
      register: job_details

    - name: Set facts for job id and datetime
      set_fact:
        job_id: "{{ job_details.stdout | from_json | json_query('results[0].summary_fields.recent_jobs[0].id') }}"
        job_finished: "{{ job_details.stdout | from_json | json_query('results[0].summary_fields.recent_jobs[0].finished') }}"

    - name: Collect the output of that job
      command: |
          curl -H "Authorization: Bearer {{ awx_token }}" -kX GET 'https://{{ host_awx_url }}/api/v2/jobs/{{ job_id }}/stdout/?format=txt'
      register: job_output

    - name: Set fact for job error
      set_fact:
        job_error: "{{ job_output.stdout | replace('\"','') }}"

    - name: Send email using Mailgun API
      uri:
        url: "https://api.mailgun.net/v3/{{ mailgun_domain_name }}/messages"
        method: POST
        user: "api:{{ mailgun_api_token }}"
        body: "from='AWX Error Report <mailgun@{{ mailgun_domain_name }}>'&to='<{{ admin_email }}>'&subject='AWX Error Report'&text='An AWX job has failed. Job ID: {{ job_id }} Job finished: {{ job_finished }} Job output: job_error'"
        #headers:
        #  api: "{{ mailgun_api_token }}"
        force_basic_auth: yes
      ignore_errors: true

    - name: Send email using Mailgun API
      command: |
          curl -s --user 'api:{{ mailgun_api_token }}' \
          https://api.mailgun.net/v3/{{ mailgun_domain_name }}/messages \
          -F from='AWX Error Report <mailgun@{{ mailgun_domain_name }}>' \
          -F to={{ admin_email }} \
          -F subject='AWX Error Report' \
          -F text='"An AWX job has failed. Job ID: {{ job_id }} Job finished: {{ job_finished }} Visit this URL to view the failed job: https://{{ host_awx_url }}/#/jobs/playbook/{{ job_id }}/output"'

# Job output: {{ job_error }}