---

- name: Copy tokens.yml file to local machine
  ansible.builtin.fetch:
    src: /data/projects/awx/tokens.yml
    dest: /tmp/tokens.yml
    flat: yes

- name: Include AWX/Automation Controller master token from awx_tokens.yml
  include_vars:
    file: /tmp/tokens.yml
  no_log: True

- name: Create a AWX session token for executing AWX modules
  awx.awx.tower_token:
    description: 'AWX Session Token'
    scope: "write"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ master_token }}"
    validate_certs: "{{ validate_certs }}"
  register: awx_session_token

- name: Add a new AWX host to the {{ org_name }} inventory
  awx.awx.tower_host:
    name: "new{{ awx_url }}"
    description: "A new AWX Server, accessed at its URL."
    inventory: "{{ org_name }}"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"
  ignore_errors: True

- name: Add new host to group awx_servers
  awx.awx.tower_group:
    name: awx_servers
    description: "AWX servers."
    inventory: "{{ org_name }}"
    hosts: "new{{ awx_url }}"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"

- name: Update 'AWX Ansible' project
  awx.awx.tower_project_update:
    name: "AWX Ansible"
    timeout: 300
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"

- name: Create 'AWX Recover [Borgmatic]' job template
  awx.awx.tower_job_template:
    name: "AWX Recover [Borgmatic]"
    description: "Recovers a borg backup of local dumps to the target AWX server."
    job_type: run
    inventory: "AWX Server"
    project: "AWX Ansible"
    playbook: "playbooks/restore_borg.yml"
    credentials: [ "AWX SSH Key", "Borgmatic Password" ]
    extra_vars: { awx_url: "{{ awx_url }}", BORG_PASSPHRASE: "{{ backup_passphrase }}", ansible_user: "borg" }
    state: present
    verbosity: 1
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"

- name: Create 'AWX Recover [Local Dump]' job template
  awx.awx.tower_job_template:
    name: "AWX Recover [Local Dump]"
    description: "Backs up the AWX host system, dumping a snapshot of it to the local disk."
    job_type: run
    inventory: "Localhost"
    project: "AWX Ansible"
    playbook: playbooks/restore_local.yml
    state: present
    verbosity: 1
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"

- name: Add machine credential
  awx.awx.credential:
    name: "AWX Root Key"
    description: "The SSH key for AWX to connect to another instance of itself."
    organization: "{{ org_name }}"
    credential_type: Machine
    state: present
    inputs:
      ssh_key_unlock: "{{ ssh_key_file_password }}"
      ssh_key_data: "{{ lookup('file', '{{ ssh_key_file_private }}') }}"
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"

- name: Create 'Provision AWX Server' job template
  awx.awx.tower_job_template:
    name: "Provision AWX Server"
    description: "Creates another AWX server with your existing AWX server."
    job_type: run
    inventory: "{{ org_name }}"
    project: "AWX Ansible"
    playbook: setup.yml
    ask_extra_vars: yes
    credential: "AWX Root Key"
    job_tags: provision
    state: present
    verbosity: 1
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"

- name: Create 'Deploy AWX Server' job template
  awx.awx.tower_job_template:
    name: "Deploy AWX Server"
    description: "Creates another AWX server with your existing AWX server."
    job_type: run
    inventory: "{{ org_name }}"
    project: "AWX Ansible"
    playbook: setup.yml
    ask_extra_vars: yes
    credential: "AWX Root Key"
    job_tags: setup, setup-firewall, master-token, configure-awx
    state: present
    verbosity: 1
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"

- name: Create 'Destroy AWX Server' job template
  awx.awx.tower_job_template:
    name: "Destroy AWX Server"
    description: "Destroys an AWX server with your existing AWX server."
    job_type: run
    inventory: "Localhost"
    project: "AWX Ansible"
    playbook: setup.yml
    ask_extra_vars: yes
    credential: "AWX Root Key"
    job_tags: deprovision
    state: present
    verbosity: 1
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"

- name: Template the backup_rehearsal.json file locally
  delegate_to: localhost
  ansible.builtin.template:
    src: roles/backup-rehearsal/surveys/backup_rehearsal.json.j2
    dest: /tmp/backup_rehearsal.json

- name: Copy current hosts inventory to /tmp/vars.yml
  delegate_to: localhost
  ansible.builtin.copy:
    src: "inventory/host_vars/{{ awx_url }}/vars.yml"
    dest: "/tmp/vars.yml"

- name: Remove line containing 'awx_url' from vars.yml
  delegate_to: localhost
  ansible.builtin.lineinfile:
    path: /tmp/vars.yml
    regexp: '^awx_url:.*$'
    state: absent

- name: Create host_awx_token variable for executing AWX modules
  delegate_to: localhost
  awx.awx.tower_token:
    description: 'AWX Session Token'
    scope: "write"
    state: present
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ master_token }}"
    validate_certs: "{{ validate_certs }}"
  register: host_awx_token

- name: Add line containing 'host_awx_token' to vars.yml
  delegate_to: localhost
  ansible.builtin.lineinfile:
    path: /tmp/vars.yml
    regexp: '^host_awx_token:.*$'
    line: 'host_awx_token: {{ host_awx_token.ansible_facts.tower_token.token }}'

- name: Add line containing 'host_awx_url' to vars.yml
  delegate_to: localhost
  ansible.builtin.lineinfile:
    path: /tmp/vars.yml
    regexp: '^host_awx_url:.*$'
    line: 'host_awx_url: {{ awx_url }}'

- name: Create 'AWX Disaster Recovery Rehearsal' workflow template
  awx.awx.workflow_job_template:
    name: "AWX Disaster Recovery Rehearsal"
    description: "Causes AWX to clone itself from its own backup, automatically provisioning the server and DNS records. It then examines if the recovered version is functional, generates a report, then deletes it."
    survey_enabled: true
    survey_spec: "{{ lookup('file', '/tmp/backup_rehearsal.json') }}"
    extra_vars: "{{ lookup('file', '/tmp/vars.yml') | from_yaml }}"
    workflow_nodes:
      - identifier: "SCM Update AWX Ansible"
        unified_job_template:
          name: "AWX Ansible"
          type: project
        related:
          success_nodes:
            - identifier: "Provision AWX Server"
          failure_nodes: []
          always_nodes: []
      - identifier: "Provision AWX Server"
        job_type: run
        unified_job_template:
          name: "Provision AWX Server"
          type: job_template
        related:
          success_nodes:
            - identifier: "Deploy AWX Server"
          failure_nodes:
            - identifier: "Error Report 1"
          always_nodes: []
      - identifier: "Deploy AWX Server"
        job_type: run
        unified_job_template:
          name: "Deploy AWX Server"
          type: job_template
        related:
          success_nodes:
            - identifier: "Recover Borgmatic"
          failure_nodes:
            - identifier: "Error Report 2"
          always_nodes: []
      - identifier: "Recover Borgmatic"
        job_type: run
        unified_job_template:
          name: "AWX Recover [Borgmatic]"
          type: job_template
        related:
          success_nodes: 
            - identifier:	"Recover Local Dump"
          failure_nodes:
            - identifier: "Error Report 3"
          always_nodes: []
      - identifier: "Recover Local Dump"
        job_type: run
        unified_job_template:
          name: "AWX Recover [Local Dump]"
          type: job_template
        related:
          success_nodes: 
            - identifier: "AWX Status Check"
          failure_nodes:
            - identifier: "Error Report 4"
          always_nodes: []
      - identifier: "AWX Status Check"
        job_type: run
        unified_job_template:
          name: "AWX Status Check"
          type: job_template
        related:
          success_nodes: []
          failure_nodes:
            - identifier: "Error Report 5"
          always_nodes: []
      - identifier: "Error Report 1"
        job_type: run
        unified_job_template:
          name: "AWX Error Report"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - identifier: "Destroy AWX Server 1"
      - identifier: "Error Report 2"
        job_type: run
        unified_job_template:
          name: "AWX Error Report"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - identifier: "Destroy AWX Server 2"
      - identifier: "Error Report 3"
        job_type: run
        unified_job_template:
          name: "AWX Error Report"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - identifier: "Destroy AWX Server 3"
      - identifier: "Error Report 4"
        job_type: run
        unified_job_template:
          name: "AWX Error Report"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - identifier: "Destroy AWX Server 4"
      - identifier: "Error Report 5"
        job_type: run
        unified_job_template:
          name: "AWX Error Report"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - identifier: "Destroy AWX Server 5"
      - identifier: "Destroy AWX Server 1"
        job_type: run
        unified_job_template:
          name: "Destroy AWX Server"
          type: job_template
      - identifier: "Destroy AWX Server 2"
        job_type: run
        unified_job_template:
          name: "Destroy AWX Server"
          type: job_template
      - identifier: "Destroy AWX Server 3"
        job_type: run
        unified_job_template:
          name: "Destroy AWX Server"
          type: job_template
      - identifier: "Destroy AWX Server 4"
        job_type: run
        unified_job_template:
          name: "Destroy AWX Server"
          type: job_template
      - identifier: "Destroy AWX Server 5"
        job_type: run
        unified_job_template:
          name: "Destroy AWX Server"
          type: job_template
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"
  ignore_errors: true

- name: Create 'AWX Disaster Recovery Rehearsal 2' workflow template
  awx.awx.workflow_job_template:
    name: "AWX Disaster Recovery Rehearsal 2"
    description: "Causes AWX to clone itself from its own backup, automatically provisioning the server and DNS records. It then examines if the recovered version is functional, generates a report, then deletes it."
    survey_enabled: true
    survey_spec: "{{ lookup('file', '/tmp/backup_rehearsal.json') }}"
    extra_vars: "{{ lookup('file', '/tmp/vars.yml') | from_yaml }}"
    workflow_nodes:
      - identifier: "SCM Update AWX Ansible"
        unified_job_template:
          name: "AWX Ansible"
          type: project
        related:
          success_nodes:
            - identifier: "Provision AWX Server"
          failure_nodes: []
          always_nodes: []
      - identifier: "Provision AWX Server"
        job_type: run
        unified_job_template:
          name: "Provision AWX Server"
          type: job_template
        related:
          success_nodes:
            - identifier: "Deploy AWX Server"
          failure_nodes:
            - identifier: "Error Report"
          always_nodes: []
      - identifier: "Deploy AWX Server"
        job_type: run
        unified_job_template:
          name: "Deploy AWX Server"
          type: job_template
        related:
          success_nodes:
            - identifier: "Recover Borgmatic"
          failure_nodes:
            - identifier: "Error Report"
          always_nodes: []
      - identifier: "Recover Borgmatic"
        job_type: run
        unified_job_template:
          name: "AWX Recover [Borgmatic]"
          type: job_template
        related:
          success_nodes: 
            - identifier:	"Recover Local Dump"
          failure_nodes:
            - identifier: "Error Report"
          always_nodes: []
      - identifier: "Recover Local Dump"
        job_type: run
        unified_job_template:
          name: "AWX Recover [Local Dump]"
          type: job_template
        related:
          success_nodes:
            - identifier: "AWX Status Check"
          failure_nodes:
            - identifier: "Error Report"
          always_nodes: []
      - identifier: "AWX Status Check"
        job_type: run
        unified_job_template:
          name: "AWX Status Check"
          type: job_template
        related:
          success_nodes: []
          failure_nodes:
            - identifier: "Error Report"
          always_nodes: []
      - identifier: "Error Report"
        job_type: run
        unified_job_template:
          name: "AWX Error Report"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes:
            - identifier: "Destroy AWX Server"
      - identifier: "Destroy AWX Server"
        job_type: run
        unified_job_template:
          name: "Destroy AWX Server"
          type: job_template
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"

#- name: Collect timezone of AWX server (Debian and derivatives only)
#  command: cat /etc/timezone
#  register: timezone_output

#- name: Create an rrule string for the 'Deploy an AWX Server'
#  set_fact:
#    rrule_line_update: "DTSTART;TZID={{ timezone_output.stdout }}:{{ update_schedule_start }} RRULE:FREQ={{ update_schedule_frequency }};INTERVAL={{ update_schedule_interval }}"

#- name: Build a schedule for 'AWX Disaster Recovery Rehearsal' workflow template
#  awx.awx.tower_schedule:
#    name: "AWX Disaster Recovery Rehearsal"
#    enabled: yes
#    state: present
#    unified_job_template: "AWX Disaster Recovery Rehearsal"
#    rrule: "{{ rrule_line_update }}"
#    tower_host: "https://{{ awx_url }}"
#    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
#    validate_certs: "{{ validate_certs }}"

- name: Delete the AWX session token for executing modules
  awx.awx.tower_token:
    description: 'AWX Session Token'
    scope: "write"
    state: absent
    existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
    tower_host: "https://{{ awx_url }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"