---

- name: Create local Prometheus datasource
  community.grafana.grafana_datasource:
    name: "{{ grafana_url }}"
    access: proxy
    ds_type: prometheus
    ds_url: 'http://{{ backup_server_ip }}:9090'
    url: "https://{{ grafana_url }}"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_default_password }}"

#- name: Create local Node Exporter datasource
#  community.grafana.grafana_datasource:
#    name: local_node_exporter
#    access: proxy
#    ds_type: prometheus
#    ds_url: 'http://{{ backup_server_ip }}:9100'
#    url: "https://{{ grafana_url }}"
#    grafana_user: "admin"
#    grafana_password: "{{ grafana_admin_default_password }}"

- name: Collect AWX Servers public IP
  community.general.ipify_facts:
  #register: public_ip

- name: Collect AWX Servers public IP
  set_fact:
    awx_public_ip: "{{ ansible_facts.ipify_public_ip }}"

- name: Create AWX Prometheus datasource
  community.grafana.grafana_datasource:
    name: "{{ awx_url }}"
    access: proxy
    ds_type: prometheus
    is_default: true
    ds_url: 'http://{{ awx_public_ip }}:9090'
    grafana_url: "https://{{ grafana_url }}"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_default_password }}"

#- name: Create AWX Node Exporter datasource
#  community.grafana.grafana_datasource:
#    name: awx_node_exporter
#    access: proxy
#    ds_type: prometheus
#    ds_url: 'http://{{ awx_public_ip }}:9100'
#    grafana_url: "https://{{ grafana_url }}"
#    grafana_user: "admin"
#    grafana_password: "{{ grafana_admin_default_password }}"

- name: Import Grafana dashboard 'Prometheus 2.0 Overview'
  community.grafana.grafana_dashboard:
    folder: General
    dashboard_url: https://grafana.com/api/dashboards/3662/revisions/2/download
    state: present
    grafana_url: "https://{{ grafana_url }}"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_default_password }}"
  ignore_errors: true

- name: Import Grafana dashboard Node Exporter
  community.grafana.grafana_dashboard:
    folder: General
    dashboard_url: https://grafana.com/api/dashboards/1860/revisions/29/download
    state: present
    grafana_url: "https://{{ grafana_url }}"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_default_password }}"

- name: Create a Grafana folder called 'K3S'
  community.grafana.grafana_folder:
    title: "K3S"
    state: present
    grafana_url: "https://{{ grafana_url }}"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_default_password }}"

- name: Import Grafana dashboard K3S cluster monitoring
  community.grafana.grafana_dashboard:
    folder: K3S
    dashboard_url: https://grafana.com/api/dashboards/15282/revisions/1/download
    state: present
    grafana_url: "https://{{ grafana_url }}"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_default_password }}"
  ignore_errors: true

- name: Import Grafana dashboard 'Kubernetes Cluster'
  community.grafana.grafana_dashboard:
    folder: K3S
    dashboard_url: https://grafana.com/api/dashboards/7249/revisions/1/download
    state: present
    grafana_url: "https://{{ grafana_url }}"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_default_password }}"
  ignore_errors: true

# This doesn't set the admin password or get you past the initial interactive prompt :/
#- name: Update admin Grafana users password
#  community.grafana.grafana_user:
#    name: "{{ org_name }} Administrator"
#    email: "{{ grafana_email }}"
#    login: admin
#    password: "{{ grafana_admin_new_password }}"
#    is_admin: true
#    state: present
#    url: "https://{{ grafana_url }}"
#    grafana_user: "admin"
#    grafana_password: "{{ grafana_admin_default_password }}"